# Generated by Django 3.2.18 on 2023-02-21 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230221_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipes',
            options={'verbose_name': 'В избранном', 'verbose_name_plural': 'Избранные рецепты'},
        ),
    ]
